### ISSUE TITLE
For mainnet

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#280]
### Todo
- [ ] https://github.com/blockstack/explorer/issues/234
- [ ] https://github.com/blockstack/explorer/issues/255
- [x] https://github.com/blockstack/explorer/issues/256
- [ ] https://github.com/blockstack/explorer/issues/257
- [ ] https://github.com/blockstack/explorer/issues/258
- [ ] https://github.com/blockstack/explorer/issues/261
- [ ] https://github.com/blockstack/explorer/issues/262
- [x] https://github.com/blockstack/explorer/issues/224

Needs more research/design
- https://github.com/blockstack/explorer/issues/244
- https://github.com/blockstack/explorer/issues/228
- https://github.com/blockstack/explorer/issues/227

**Comment by agraebe** [comment]
@aulneau- did we complete all of the above?
